# Replace old mailbaby_smarthost router with this router when MailBaby is used.
mailbaby_log_smarthost:
  driver = manualroute
  domains = ! +local_domains
  transport = log_and_send_smtp
  route_list = * relay.mailbaby.net::587 byname
  no_more

# SMTP transport with logging filter.
log_and_send_smtp:
  driver = smtp
  hosts_require_auth = relay.mailbaby.net
  hosts_require_tls = relay.mailbaby.net
  transport_filter = /usr/local/bin/log_outbound_mail.php
